# Generated by Django 4.1.13 on 2025-07-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'Student'},
        ),
    ]
