# Generated by Django 4.1.13 on 2025-07-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
